### ISSUE TITLE
Limit total threads based on device 'capabilities'?

### ISSUE THREAD

**Issue by wilsonpage** [gaia-components/threads#12]
Somehow we will derive a magic number of 'ideal number of threads'. This could be given at build time, or derived at runtime from some web-api. We then want to use this number to dictate the thread architecture.

We will keep creating new threads (`Windows`, `Workers`, `SharedWorkers`) until this number is reached. At which point, any further services should be 'injected' into pre-existing threads by the manager.

``` js
thread.loadService('path/to/service.js');
```

**Comment by millermedeiros** [comment]
are you sure this is needed? shouldn't Gecko be smarter than us on the resource allocation? (just wondering about added complexity and if there is going to be any real gain)

**Comment by wilsonpage** [comment]
You might be right. Let's try to get feedback from Vivien.

**Comment by wilsonpage** [comment]
> It turns out there is a spec to get the number of cores using JavaScript:
> navigator.hardwareConcurrency (implemented in Chrome)
> https://wiki.whatwg.org/wiki/Navigator_HW_Concurrency
> 
> There is also a script to estimate this number:
> https://github.com/oftn/core-estimator
> @gmarty
