### ISSUE TITLE
Stream is a misleading name for the thing that is currently service.stream()

### ISSUE THREAD

**Issue by lambdabaa** [gaia-components/threads#16]
What we have is just the ability for a single consumer to observe and unobserve a topic. This is useful, but calling it `stream` is misleading and will make people think that it does things that it doesn't. How about `service.channel(topic)` or `service.observe(topic)` or `service.observable(topic)`?

See https://github.com/whatwg/streams/issues/341.

**Comment by millermedeiros** [comment]
I agree that it's a bad name, I just couldn't think of a better one at the time; [quoting myself](https://github.com/gaia-components/threads/issues/6#issuecomment-94187041):

> "... Maybe we even use a different name than streams to avoid confusion, but for now it's good enough.
> Shipped is better than perfect."

It's confusing because with streams people will assume we have _backpressure_ and _piping_ support.. (even tho we make it clear that we don't [on the README](https://github.com/gaia-components/threads/blame/909c5e4f1d9443ec403e34df68c73d50f482bbe3/README.md#L148-L153))

I like `channel` but don't know if that would be confusing since we use `BroadcastChannel` and have a few `channel` references on the source code, another option would be `tunnel`.

**Comment by lambdabaa** [comment]
How about `observe()`?

**Comment by wilsonpage** [comment]
'Observe' sounds like a persistent thing. My understanding of a stream is
something that has a start, middle and end.

**Comment by lambdabaa** [comment]
It is persistent... until you call cancel?

**Comment by lambdabaa** [comment]
The thing @millermedeiros implemented doesn't have an end, right? It's just a subscription (like a broadcast subscription except that only one subscriber is called instead of all of the subscribers to a topic being called)

**Comment by wilsonpage** [comment]
No, until the service has finished delivering all the goods. Clients can
cancel, but that is an edge case.

**Comment by lambdabaa** [comment]
Hrm okay. Miller and I had a pretty in-depth discussion last week about some calendar api work we're doing where I proposed having api endpoints for values that consumers would read and then want updates to look like this

``` js
service.on('value', value => {
  // Gets called immediately with the current value when listener is added
  // And additionally gets called when the value changes
});
```

We could do this with regular threads.js events except that there is no way for the service to know that someone subscribed to their event (like node's `onNewListener`) or be able to invoke the listener with the first value. Miller proposed we just use the recent `stream()` mechanism as a one-way, persistent channel between the service and the client, but I don't want calendar to call something stream that doesn't behave like http://www.w3.org/TR/streams-api/ or https://nodejs.org/api/stream.html. What would you recommend for us?

**Comment by wilsonpage** [comment]
So you need a `service` to be notified when a client subscribes to an event? Although a `stream` isn't a `Stream`, I think the naming is the best we have right now to explain how that particular API works.

**Comment by wilsonpage** [comment]
For your example:

``` js
service.on('value', value => {
  // Gets called immediately with the current value when listener is added
  // And additionally gets called when the value changes
});
```

I suggest you do:

``` js
service.method('getFoo').then(foo => ...);
service.on('foochanged', foo => ...);
```

We want the library to be as low level as possible. If you need extra sugar perhaps you can wrap or extend the `Client` API?

**Comment by lambdabaa** [comment]
> We want the library to be as low level as possible. If you need extra sugar perhaps you can wrap or extend the Client API?

I think that it might be helpful to contributors to understand exactly what it is that we want here. This library itself abstracts the lowest-level web apis that exist for spawning and managing multiple javascript contexts. To what level and in which ways is it helpful for threads to abstract them and why?

Speaking to my use-case in particular, providing a reactive api that calls clients with a current value at subscription time and continues to call clients with updated values enables programming the client in a _declarative_ style which is something that we're striving for at every level in calendar for the next release. If that's antithetical to threads' immediate-term goals then I think we'll probably fall back on Miller's original plan (to use the `stream()` api even though what we're providing is an observable / subscription style api and not a stream).

**Comment by wilsonpage** [comment]
The intention is to provide an easy way to spawn and communicate with services that live in separate threads. Communication currently includes:
1. Calling methods
2. Listening for events
3. Requesting 'stream like' objects that return chunks of data and then close.

It seems like you're asking for a combination of `1.` and `2.` like:

``` js
var client = threads.client('my-service');
client.method('getFoo').then(foo => ...);
client.on('foochanged', foo => ...);
```

Can you clarify why the above isn't acceptable?

**Comment by lambdabaa** [comment]
There's a nice but brief discussion on reactive programming [here](http://en.wikipedia.org/wiki/Reactive_programming). The idea here is that we don't want to write and maintain logic to get and respond to changes in readable values but instead for our frontend code to specify how, given an up-to-date view of the application state, we should display things. http://facebook.github.io/react/ is an excellent, related frontend library. The underlying principle is that your frontend code will be simpler and easier to reason about if you compose your UIs from observable/reactive data sources rather than maintaining a lot of state yourself and writing code to update the UI appropriately when one of _x_ different things happens and the application is in one of _y_ different states.

**Comment by gaye** [comment]
Er I submitted that last comment before I was done writing... updating now.

**Comment by wilsonpage** [comment]
Are you asking for a 4th API, `client.getAndObserve()`?

**Comment by lambdabaa** [comment]
Perhaps? I think Miller's code is very close to what I want except that the function names are misleading. I also prefer `observe()` to `getAndObserve()` but either is better than `stream()`.

**Comment by wilsonpage** [comment]
`.observe()` makes sense for your particular use-case, but not all. This is a library for all Gaia apps. If you require additional sugar/opinion I suggest you extend or wrap.

**Comment by lambdabaa** [comment]
Okay will close. Thanks for being thoughtful in trying to understand and engage with what we want in calendar. I appreciate that :+1:.

**Comment by wilsonpage** [comment]
Sorry I couldn't be of more help, just trying to keep everyone happy :disappointed:
