### ISSUE TITLE
Provide fallback/polyfill when BroadcastChannel doesn't exist

### ISSUE THREAD

**Issue by gmarty** [gaia-components/threads#3]
Let's make sure `BroadcastChannel` is defined before used or non supporting environments will complain.

**Comment by wilsonpage** [comment]
Options:
- `SharedWorker` to relay all messages. Not sure if it's possible to create `SharedWorker` from a `Worker` yet though.
- `localStorage` events via `window.addEventListener('storage', ...)`. Is `localStorage` accessible from workers?

**Comment by wilsonpage** [comment]
Once `MessageChannel` support lands in gecko we could look at migrating away from `BroadcastChannel` as our primary transport mechanism.

This is likely to add complexity to the library as we will have to 'manually' locate the desired `Service` for the `Client` so we can pass it the `Client`'s `MessagePort` object. This would likely entail us walking each of the threads in the origin, querying for a matching service name.

Once the Service has been discovered, message passing would be simple. We need to establish whether this connection procedure would be too costly or not.

@gmarty do you have any thoughts?
