### ISSUE TITLE
Make service endpoints more entensible

### ISSUE THREAD

**Issue by wilsonpage** [gaia-components/threads#42]
Right now we have three endpoint types:
- `Worker`
- `SharedWorker`
- `Window`

We should make this extensible so that users can create their own endpoints, as Services could live inside `ServiceWorkers` or even other apps via `navigator.connect()`. As a result is might be better for managers to look more like:

``` js
threads.manager({
  'service-1': () => threads.Worker('my-services/service-1.js'),
  'service-2': () => threads.SharedWorker('my-services/service-2.js'),
  'service-3': () => threads.Window('my-services/service-3.js'),
  'service-4': () => MyCustomEndpoint()
});
```

The Manager would just expect the function to return an object with standard properties, such as:
- `postMessage()`
- `onmessage`
- etc

This could be more efficient as it would mean the user would only have to load the logic for the endpoints that they need.

**Comment by gmarty** [comment]
I like the idea for its advantages in terms of extensibility and optimisation.

**Comment by wilsonpage** [comment]
Endpoints would require two scripts, one to create the endpoint and send/receive messages to it, and another to operate _inside_ to receive the messages and send back replies:
- `worker-endpoint.js`
- `worker-endpoint-child.js`

**Comment by wilsonpage** [comment]
Theoretically we could remove the usage of `BroadcastChannel` (good for cross-browser) if Clients knew what thread the manager was in.

#### Global reference

``` js
Client.prototype.manager = new WindowEndpoint('my-manager.html');

var myClient1 = new Client('my-service-1');
var myClient2 = new Client('my-service-2');
```

#### Per instance reference

``` js
var myManager = new WindowEndpoint('my-manager.html');
var myClient = new Client('my-service', { manager: myManager });
```

#### Without manager altogether

``` js
var myClient = new Client('my-service', new WorkerEndpoint('my-worker.js'));
```

**Comment by wilsonpage** [comment]
If we begin to look at `endpoint`s as being a pointer to a thread that the `Service` lives in, we can start using it to route requests through various threads. The `Manager` itself can be an `endpoint` routing requests to their final endpoint.

This means `Client` doesn't even have to know about `Manager` and the above example will start to look something like:

#### Global endpoint

``` js
Client.prototype.endpoint = new WindowEndpoint('my-manager.html');
var myClient1 = new Client('my-service-1');
var myClient2 = new Client('my-service-2');
```

#### Per instance endpoint

``` js
var myClient = new Client({
  service: 'my-service',
  endpoint: new WorkerEndpoint('my-worker.js')
});
```
