### ISSUE TITLE
threads.create is not a function

### ISSUE THREAD

**Issue by lambdabaa** [gaia-components/threads#49]
It used to be a function though...

**Comment by wilsonpage** [comment]
The V1 release made some breaking changes. The core library is lighter and only concerned with exposing and digesting services, when previously it handled the creation and destruction of 'threads'.

I imagine we will want this functionality in Gaia, but it will likely be in the form of a helper library that uses threads.js under the hood.

**Comment by lambdabaa** [comment]
Okay I'll stick on the v0 branch for now until I find some time to digest
the changes. Thanks for the info.
