### ISSUE TITLE
bikeshed: rename client.call() into something else?

### ISSUE THREAD

**Issue by millermedeiros** [gaia-components/threads#5]
because of [Function.prototype.call](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call) it's kinda confusing. maybe `run` or `exec`?

``` js
client.run('myMethod', 'world');
client.exec('myMethod', 'world');
```

**Comment by wilsonpage** [comment]
I completely "call" with this! :smile:

**Comment by wilsonpage** [comment]
I should also mention that in an earlier version we tried using `Proxy` to allow method calls the look like:

``` js
client.myMethod('world');
```

IMO this is a little misleading as `myMethod` doesn't actually exist and also adds additional complexity for 'sugar' sake.

**Comment by wilsonpage** [comment]
Another option:

``` js
client.method('myMethod', 'world');
```

As this maps well to the 'contract' format (`{ methods: {...}, events: {...} }`)

**Comment by millermedeiros** [comment]
`method` sounds good to me, better than other options. :+1:
