### ISSUE TITLE
Chrome support?

### ISSUE THREAD

**Issue by lambdabaa** [gaia-components/threads#50]
Chrome doesn't have BroadcastChannel yet and I know that support for non-FF environments came up at some point as a project goal

**Comment by gmarty** [comment]
Yes, the goal is to get rid of Broadcast Channel to make it completely cross-browser compatible.

**Comment by wilsonpage** [comment]
The v1 release removed `BroadcastChannel` as a core dependency, migrating towards widely supported `MessageChannel` API.
