### ISSUE TITLE
better way to handle batches/streams?

### ISSUE THREAD

**Issue by millermedeiros** [gaia-components/threads#6]
for the Calendar app we need to expand the _busytimes_ (same event might repeat multiple times), so a basic calendar sync might trigger thousands of expansions..

waiting for the whole operation to complete before we display the events to the user is not really a good approach (might take many seconds to finish the sync), so we really need some sort of event listener that allow us to handle busytimes in batches (maybe queue 10-100 busytimes before dispatching an event) and/or a way to handle busytimes as they are expanded (emit one event for each busytime).

we also need a way to know that the whole expansion/sync finished.

I guess SMS and Contacts would also need something similar.

**Comment by millermedeiros** [comment]
my first thought is to create a new _kind_ of service that instead of returning a `Promise` would return an `EventEmitter` that dispatches `data`, `error` and `end` events (similar to a node.js `stream.Readable`).

the main problem is that the client would need to know that the service is _special_ and doesn't return a `Promise`... maybe we should have 2 methods to avoid confusions (one for calling regular methods, and another one for opening _streams_)

**Comment by millermedeiros** [comment]
right now we could emit events on the `service` itself, but it's weird to have to deal with the listeners and to dispatch events that are theoretically global, currently the code would need to look similar to this:

``` js
var client = threads.client('calendar-events');

client.on('busytime', logBusytime);
client.on('busytimeError', handleError);
client.call('expand', timeRange).then(() => {
  client.off('busytime', logBusytime);
  client.off('busytimeError', handleError);
  console.log('complete');
});
```

**Comment by wilsonpage** [comment]
Agreed I think we need something like this.

Your examples aren't that clear to me though, I don't know what 'busytimes' or 'expansions' are. Can you provide a more generic (non-calendar) example?

I'm sure we can add a second method type something like:

``` js
client.stream('contacts')
  .on('data', ...)
  .on('error', ...)
  .on('end', ...);
```

What do you think?

(thanks for your help on this Miller :smiley:)

**Comment by millermedeiros** [comment]
@wilsonpage that is exactly what I had in mind. a new method that returns an `EventEmitter` instead of a `Promise`, chaining is a good sugar.

On the Calendar when you create an `event` you can set it to repeat N times, each one of the occurrences is called a `busytime`. We call the conversion between a single `event` into N `busytimes` an _expansion_. Synching hundreds of events from the server can easily generate thousands of busytimes and some expansions are very complex ([RRULE](https://tools.ietf.org/html/rfc2445#section-4.8.5.4))

**Comment by julienw** [comment]
Actually the SMS app use case is currently a little more complex because we also want the ability to stop the stream (and to stop the code generating that stream).

But otherwise this looks good to me as well.

I don't know how this can relate to CSP or any Streaming API or ProgressPromise or however it's called in the work for "fetch"?

**Comment by millermedeiros** [comment]
on Calendar we also need the ability to stop/kill the stream, just unsure on what would be the best way to do it. To me it feels like this should be handled by the `service` not the `client` (calling `stream('contacts')` twice would stop the first execution, or `method('stopContactStream')`). Maybe we need some other shared abstraction for this kind of rule since it's so common, but I don't think it should live inside this lib... (single responsibility)

Since cancel/stop/kill is common should it also emit a `cancel` event? Or maybe `error` with a custom message is enough? maybe we can emit any custom event?

PS: I'm creating more questions than answers on purpose, just so we can get a better idea of what problems we are trying to solve.

**Comment by wilsonpage** [comment]
Any ideas on what the server-side API should look like?

**Comment by julienw** [comment]
maybe the function could return a Stream object, that has a "emit" function and we can register to a "cancel" event (and also "error" ?). The customer could also "emit" a "cancel" and register to "data", "end", "error" events.

**Comment by wilsonpage** [comment]
The current API may have to be adapted to accommodate serving 'stream like' things. I've never really used streams, so this is a naive idea:

``` js
threads.service('my-service')
  .method('my-method', arg => 'hello ' + arg)
  .stream('contacts', stream => {
    stream.send('stuff');
    stream.send('more stuff');
    stream.close();
  });
```

**Comment by millermedeiros** [comment]
I like the idea of the service API being split into multiple `method` and `stream` calls (specially when file have lots of methods), but I don't think the stream should be created _automagically_; `client` will probably need to pass arguments in this case as well.

The cancellation could be handled by the service like:

``` js
// inside a worker
var contactsStream;

threads.service('my-service')
  // allow explicit cancelation if needed
  .method('stopLoadingContacts', stopLoadingContacts)
  .stream('contacts', (start, end) => {
    var stream = threads.stream();
    // implicit cancelation of previous action if it's still running
    stopLoadingContacts();
    contactsStream = stream;
    stream.on('end', () => contactsStream = null);
    loadContactsAsynchronously(start, end, stream);
    return stream;
  });

function stopLoadingContacts() {
  if (!contactsStream) return;
  contactsStream.emit('end');
  // ...
}
```

``` js
// on the client
var client = threads.client('my-service');

function loadAndShowContacts(start, end) {
  showProgress();
  client.stream('contacts', start, end)
    .on('data', addContact)
    .on('error', showError)
    .on('end', hideProgress);
}
```

We could abstract the automatic cancellation logic, but as you can see, it only takes ~6 lines of code for the basic state logic... not sure if we can justify it and if it would fit all the scenarios -- in some cases cancellation needs to be async, in others calling multiple times the same method should not cancel (in some cases we might even need some sort of state machine...)

On the calendar app right now the worker emits some custom events (`occurrence`, `component`, `event`, `missingEvents`) but I guess it could be handled by a single `data` event that passed an object with a property `type`. I think that keeping it with only `data`, `error` and `end` should be good enough and reduce complexity (`cancel` event seems redundant)..

**Comment by julienw** [comment]
So you propose to cancel a previous call's stream by calling another service? This gives more complex client code, and less complex lib code. I don't think this is the right balance...

On a more generic approach, do we want to make it possible to enable a bidi stream between customer and service? (ala websocket, if we want to keep the HTTP metaphor)

**Comment by julienw** [comment]
see also the discussion about AbortableProgressPromise in https://groups.google.com/forum/#!topic/mozilla.dev.webapi/N1FjiEqCflI

**Comment by millermedeiros** [comment]
Now I agree with @julienw we should at least have a `close` or `abort` method on the stream. Specially for cases where we have multiple clients using the same service.

**Comment by wilsonpage** [comment]
### Client API

``` js
var stream = client.stream('contacts', { some: 'data' })
  .on('data', ...)
  .on('error', ...)
  .on('end', ...);

// In the event the stream hasn't ended
// and is no longer required
stream.close();
```

### Service API

``` js
threads.service('my-service')
  .stream('contacts', stream => {
    stream.data; //=> { some: 'data' }

    // In the event the client closes the stream
    stream.on('close', cancelEverything);

    stream.send('stuff');
    stream.send('more stuff');
    stream.close();
  });
```

**Comment by wilsonpage** [comment]
Not sure how the `'error'` event should be triggered from the serverside. Should we just `catch` exceptions and pipe them back?

**Comment by wilsonpage** [comment]
This is blocked by #10.

**Comment by julienw** [comment]
> Not sure how the 'error' event should be triggered from the serverside. Should we just catch exceptions and pipe them back?

I don't know if you could catch everything. Wondering if the service could send an "error" event explicitely as well?

Proposal: replace `on('end')` with `on('close')` on the customer side.

**Comment by millermedeiros** [comment]
I'll work on this feature on Monday. Have 2 PRs open at the moment waiting
for review (that blocks this), was going to start on Friday but got
sidetracked...

I was thinking about the `stream.close()` being named `stream.abort()` to
make it clearer that you are canceling the action and not simply "closing"
the channel but will try to follow other stream implementations/specs.

I'll try to follow https://github.com/whatwg/streams even if our "streams"
don't really implement the same features. -- For now I think we should keep
it as simple as possible and increase complexity as needed. Maybe we even
use a different name than streams to avoid confusion, but for now it's good
enough.

Shipped is better than perfect.

**Comment by julienw** [comment]
Totally agree.

I was only wondering when the "end" event would be sent to the client, and I thought it would be when the stream would be closed on the server side, and that's why I thought that "close" would be more meaningful.

**Comment by millermedeiros** [comment]
Yes, I agree. On the server side it is not an `abort` in most cases, if the
action completed with success it should be something like `end` or `close`.

**Comment by julienw** [comment]
yeah, that's why I thought that "close" on both sides (both the method call and the event name) makes sense -- I don't think there is a need to have more meaning and semantic for now.

**Comment by millermedeiros** [comment]
just a FYI, I ended up implementing a different API then the one discussed above after reading the whatwg spec. the PR #15 now looks like:

## Client API

``` js
var stream = client.stream('contacts', { some: 'data' });
stream.listen(onData);
stream.unlisten(onData);
stream.closed.then(onClose, onAbort);
stream.cancel('because I want').then(doStuffAfterCancel).catch(onCancelError);
```

## Service API

``` js
threads.service('my-service')
  .stream('contacts', (stream, data) => {
    stream.cancel = cancelEverything;
    if (data.foo === 123) return stream.abort('invalid argument');
    stream.write('stuff');
    stream.close();
  });
```

**Comment by julienw** [comment]
I like it :)
