### ISSUE TITLE
Lib minimized with "--compilation_level=ADVANCED_OPTIMIZATIONS" doesn't work

### ISSUE THREAD

**Issue by azasypkin** [gaia-components/threads#76]
I've tried to compile lib with:

```
ccjs bridge.js --language_in=ECMASCRIPT6 \
               --language_out=ES5 \
               --compilation_level=ADVANCED_OPTIMIZATIONS \
               > bridge.min.js
```

And I see errors like `Error: Unable to establish a connection with "undefined". Either the target endpoint is not alive or the Service is not `.listen()`ing.`.

While everything works ok with:

```
ccjs bridge.js --language_in=ECMASCRIPT6 \
               --language_out=ES5 \
               --compilation_level=SIMPLE_OPTIMIZATIONS \
               > bridge.min.js
```

As the test app I've used https://github.com/nga-crash-tests/bridge-local-broadcast-channel hosted locally.

**Comment by wilsonpage** [comment]
Found out CC was mangling the `options.service` property when using the options object.

**Comment by wilsonpage** [comment]
Not sure why it wasn't mangling the other two. Perhaps to do with all the funkyness going on in constructor, maybe we should simplify that to limit code paths.
