### ISSUE TITLE
Support DOMError instance in client/service method reject

### ISSUE THREAD

**Issue by steveck-chung** [gaia-components/threads#80]
Currently the method could support basic error instance in reject that client side could get the error message directly in method reject, but for DOMError the method will be failed in dataclone error. Considering the DOMError is commonly used in our WebAPI, it would be better if bridge could deal with dataclone issue instead of cloned/handled by service itself.

**Comment by wilsonpage** [comment]
Can you provide a code example?

**Comment by steveck-chung** [comment]
Ok, imaging it's a iframe service(because we need to access webAPI)

```
service('mobile-message-shim')
  .method('retrieveMMS', (id) => {
     return navigation.mozMobilemessage.retrieveMMS(id).then((message) => {
       // clone the message
       return clonedMessage(message);
     }) 
   })
```

But it will be failed when API return error(no responding client side) because the error is DOMError instance and it's not clone-able object for communication. Maybe you already deal with the normal error instance because if the error here is basic Error instance, client side will receive reject with error's message. So in this case I can workaround like:

```
     return navigation.mozMobilemessage.retrieveMMS(id).then((message) => {
       // clone the message
       return clonedMessage(message);
     }, (error) => {
       throw error.name; // or throw { name: error.name } to keep the same structure
     })
```

Since DOMError is quite common in our apps, I think maybe it's possible to make deal with this problem in bridge level instead of destructing the DOMError in app level?

**Comment by wilsonpage** [comment]
Do you know of a standard Dom API (not special moz api) that I can use in
unit-tests to reproduce this problem?

**Comment by steveck-chung** [comment]
Maybe you can try to reject with DOMError[1] instance like `new DOMError('fakeError')` in the unit test

[1] https://developer.mozilla.org/en/docs/Web/API/DOMError

**Comment by julienw** [comment]
Do we have a bugzilla bug to request that DOMError is cloneable ?

**Comment by steveck-chung** [comment]
Seems no (just a quick search)

**Comment by julienw** [comment]
Can we resume work on this ?
