### ISSUE TITLE
Service.destroy fails with "too much recursion" when it's called inside SharedWorker 

### ISSUE THREAD

**Issue by azasypkin** [gaia-components/threads#89]
1. Open [1];
2. Click on "Call Method";
3. Go to about:debugging, enable debugging of workers and start debugging worker created on the step 1;
4. Put break point in [2] and go back to the page;
5. Click on "Dispose" and waits until you break point is fired.

From what I saw it looks like in [3] we have 3 ports for some reason (likely not related, but wondering why do we have 3 ports here, @wilsonpage :)) and when we call `port.removeListener(this.onMessage, this.unlisten);` it recursively calls the same `unlisten` again [4].

[1] http://nga-crash-tests.github.io/bridge-disposable/
[2] https://github.com/nga-crash-tests/bridge-disposable/blob/master/js/services/shared-worker-service.js#L29
[3] https://github.com/nga-crash-tests/bridge-disposable/blob/master/js/libs/bridge/service.js#L500
[4] https://github.com/nga-crash-tests/bridge-disposable/blob/master/js/libs/bridge/service.js#L760

**Comment by wilsonpage** [comment]
I actually spotted this bug last week and I _think_ I fixed it as part of [this commit](https://github.com/gaia-components/bridge/commit/5838b485939c4c40b23a15b6e5bf05dcbd109b79).

@azasypkin please bump to `v1.1.0` and check to see if this is still an issue :)

**Comment by azasypkin** [comment]
Cool, let me check!

**Comment by azasypkin** [comment]
Yay, it seems the issue is fixed, thanks!

Fixed via https://github.com/gaia-components/bridge/commit/5838b485939c4c40b23a15b6e5bf05dcbd109b79
